### ISSUE TITLE
Add support for message stream archival

### ISSUE THREAD

**Issue by pgraham3** [ActiveCampaign/postmark-rails#80]
Need to implement the new endpoints for message stream archive and unarchive.

https://postmarkapp.com/developer/api/message-streams-api#archive-a-message-stream

https://postmarkapp.com/developer/api/message-streams-api#unarchive-a-stream

**Comment by ibalosh** [comment]
on it

**Comment by balvig** [comment]
Looks like this was handled in https://github.com/ActiveCampaign/postmark-gem/pull/109, but let me know if something's still missing!
