### ISSUE TITLE
Postmark::InactiveRecipientError No Error Recipients

### ISSUE THREAD

**Issue by rmaspero** [ActiveCampaign/postmark-rails#93]
Hi,
I've previously used the rescue described in your documentation [here](https://github.com/ActiveCampaign/postmark-rails/wiki/Error-Handling) to capture when a recipient is marked as inactive and up a failure count in our database. 

However recently I noticed that nothing was happening. After a bit of a look `error.recipients` was returning an empty array instead of who the email was sent to. I can still get the recipients from `message.recipients` though.

This is the error object I get
```
#<Postmark::InactiveRecipientError: You tried to send to recipient(s) that have been marked as inactive. Found inactive addresses: test@bounce-testing.postmarkapp.com. Inactive recipients are ones that have generated a hard bounce, a spam complaint, or a manual suppression.>
```

I also noticed the rescue is not triggered when the email is added to the list only when I try and resend.

I wanted to check what the expect behaviour of this was? and if `error.recipients` should return the same as `message.recipients`

**Comment by balvig** [comment]
Hello @rmaspero and so sorry for the belated response!

Looks like this may have been related to https://github.com/ActiveCampaign/postmark-gem/pull/131

Could you maybe try updating using `bundle update postmark` and see if the problem persists?
