### ISSUE TITLE
Wrong documentation link

### ISSUE THREAD

**Issue by PhilippGsell** [ActiveCampaign/postmark-rails#99]
first link in: 
    https://github.com/ActiveCampaign/postmark-rails/wiki/Email-sending
should link to:
    https://postmarkapp.com/developer/user-guide/send-email-with-api 
(or https://postmarkapp.com/developer/user-guide/send-email-with-smtp)

instead of https://postmarkapp.com/developer/developer-build.html#attachments

**Comment by balvig** [comment]
@PhilippGsell thanks a ton for pointing this out! 🙏 
This has now been fixed. 🙌
